### ISSUE TITLE
Files no longer available on Nexusmods:   Aspen bush size fix-26319-1-0-1589483204.7z 

### ISSUE THREAD

**Issue by Sarkovski** [ForgottenGlory/Dungeons-Deviousness#13]
Doing a fresh Install of D&D via Wabberjack the Installation failed due to files being no longer available:

29,43 - Unable to download Ember HD Patch-1863-0-1-Beta-1559201165.rar (NexusDownloader+State|SkyrimSpecialEdition|1863|94126)
29,43 - Unable to download Aspen bush size fix-26319-1-0-1589483204.7z (NexusDownloader+State|SkyrimSpecialEdition|26319|139973)

**D&D Version**
D&D Alpha 5, Wabberjack 2.2.0.0

**Describe the bug**
Installation failes due to missing files

**To Reproduce**
Restart Installation, when Download resumes same Error

**Expected behavior**
Installation Process continues

**Additional context**
Current Log Wabberjack:
0,15 - Wabbajack Build - 9d3f36559eeca5ce4fc039eab16cd83efc8bebf2
0,15 - Running in C:\Wabbajack\2.2.0.0
0,17 - Detected Windows Version: 6.2.9200.0
0,17 - System settings - (31,8GB RAM), Display: 1920 x 1080 (7,8GB VRAM - VideoMemorySizeMb=10240)
0,18 - Total number of Steam Libraries found: 0
0,18 - Searching for Steam Games in c:\steam\steamapps

0,24 - Wabbajack.Common.StoreHandlers.StoreException: Could not open the BethNetPath registry key!
0,24 - Wabbajack.Common.StoreHandlers.StoreException: Could not Init the BethNetHandler, check previous error messages!
0,45 - Wabbajack Version: 2.2.0.0
1,21 - Build server is alive
1,22 - File hash check (-42) a56b4f8ed6cd22839eac2ffdba6e887de3f7a02549811b6ff3bacfc92b5d31b2
7,13 - Starting to install Dungeons & Deviousness
7,15 - Cleaning VFS, this may take a bit of time
7,18 - Starting Installer Task
7,18 - Installation has Started
7,18 - File hash check (-42) a56b4f8ed6cd22839eac2ffdba6e887de3f7a02549811b6ff3bacfc92b5d31b2
8,2 - Configuring Processor
8,21 - Benchmarking C:\Wabbajack\2.2.0.0
8,21 - 1,5GB/sec for C:\Wabbajack\2.2.0.0
8,21 - Recommending a queue size of 12 based on disk performance, number of cores, and 31,8GB of system RAM
8,22 - Drive watcher is starting. Will warn at 8GB and error at 4GB
8,22 - Starting Drive watcher on C:\ currently 188GB free out of 926,1GB
8,22 - Starting Drive watcher on c:\ currently 188GB free out of 926,1GB
8,22 - Validating Game ESMs
8,23 - Validating Modlist
8,23 - Loading server whitelist
8,4 - Loaded permissions for 205 servers and 76 Google Drive files
8,4 - Running validation checks
8,4 - No validation failures
8,4 - Optimizing ModList
8,4 - Optimizing ModList directives
9,66 - Looking for files to delete
9,69 - Cleaning empty folders
10,27 - Looking for unmodified files
21,12 - Updating ModList
21,12 - Optimized 111314 directives to 111314 required
21,14 - Hashing Archives
21,14 - Looking for files to hash
21,15 - Found 571 files to hash
21,23 - Downloading Missing Archives
21,23 - Missing 2 archives
21,23 - Getting Nexus API Key, if a browser appears, please accept
21,88 - Downloading Aspen bush size fix-26319-1-0-1589483204.7z
21,88 - Downloading Ember HD Patch-1863-0-1-Beta-1559201165.rar
21,98 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 92
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 104
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 22
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in c:\agent\_work\1\s\Wabbajack.Lib\NexusApi\NexusApi.cs:line 272
21,98 - Ember HD Patch-1863-0-1-Beta-1559201165.rar - Error getting Nexus download URL - Http Error NotFound - Not Found
21,99 - Wabbajack.Common.Exceptions.HttpException: Http Error NotFound - Not Found
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 92
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 104
   at Wabbajack.Lib.Http.Client.GetAsync(String url, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 22
   at Wabbajack.Lib.NexusApi.NexusApiClient.Get[T](String url, Client client) in c:\agent\_work\1\s\Wabbajack.Lib\NexusApi\NexusApi.cs:line 272
21,99 - Aspen bush size fix-26319-1-0-1589483204.7z - Error getting Nexus download URL - Http Error NotFound - Not Found
23,98 - Trying to find solution to broken download for Aspen bush size fix-26319-1-0-1589483204.7z
23,99 - Trying to find solution to broken download for Ember HD Patch-1863-0-1-Beta-1559201165.rar
26,91 - Downloading Nexus Archive - SFO updated lod-26319-1-0-1593380478.7z - SkyrimSpecialEdition - 26319 - 147872
27,31 - Downloading Nexus Archive - Sneak Tools 0.6A-1863-0-6A.rar - SkyrimSpecialEdition - 1863 - 3370
27,57 - Looking for patch for Aspen bush size fix-26319-1-0-1589483204.7z (506503071732580976 70c24334dc750707 -> -1629607033678440446 02581e72097962e9)
28,38 - Looking for patch for Ember HD Patch-1863-0-1-Beta-1559201165.rar (1446882333758813314 82747b0fd15b1414 -> 1940095993344677935 2fd877e1069bec1a)
28,63 - Download error for file Aspen bush size fix-26319-1-0-1589483204.7z
28,64 - Wabbajack.Common.Exceptions.HttpException: Http Error BadRequest - Bad Request
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 92
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 104
   at Wabbajack.Lib.Http.Client.PostAsync(String url, HttpContent content, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 35
   at Wabbajack.Lib.ClientAPI.GetModUpgrade(Archive oldArchive, Archive newArchive, Nullable`1 maxWait, Nullable`1 waitBetweenTries, Boolean useAuthor) in c:\agent\_work\1\s\Wabbajack.Lib\ClientAPI.cs:line 101
   at Wabbajack.Lib.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination) in c:\agent\_work\1\s\Wabbajack.Lib\Downloaders\DownloadDispatcher.cs:line 129
   at Wabbajack.Lib.AInstaller.DownloadArchive(Archive archive, Boolean download, Nullable`1 destination) in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 309
29,37 - Download error for file Ember HD Patch-1863-0-1-Beta-1559201165.rar
29,37 - Wabbajack.Common.Exceptions.HttpException: Http Error BadRequest - Bad Request
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 92
   at Wabbajack.Lib.Http.Client.SendAsync(HttpRequestMessage msg, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions, Boolean retry) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 104
   at Wabbajack.Lib.Http.Client.PostAsync(String url, HttpContent content, HttpCompletionOption responseHeadersRead, Boolean errorsAsExceptions) in c:\agent\_work\1\s\Wabbajack.Lib\Http\Client.cs:line 35
   at Wabbajack.Lib.ClientAPI.GetModUpgrade(Archive oldArchive, Archive newArchive, Nullable`1 maxWait, Nullable`1 waitBetweenTries, Boolean useAuthor) in c:\agent\_work\1\s\Wabbajack.Lib\ClientAPI.cs:line 101
   at Wabbajack.Lib.Downloaders.DownloadDispatcher.DownloadWithPossibleUpgrade(Archive archive, AbsolutePath destination) in c:\agent\_work\1\s\Wabbajack.Lib\Downloaders\DownloadDispatcher.cs:line 129
   at Wabbajack.Lib.AInstaller.DownloadArchive(Archive archive, Boolean download, Nullable`1 destination) in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 309
29,37 - Hashing Remaining Archives
29,37 - Looking for files to hash
29,37 - Found 571 files to hash
29,43 - Unable to download Ember HD Patch-1863-0-1-Beta-1559201165.rar (NexusDownloader+State|SkyrimSpecialEdition|1863|94126)
29,43 - Unable to download Aspen bush size fix-26319-1-0-1589483204.7z (NexusDownloader+State|SkyrimSpecialEdition|26319|139973)
29,43 - Cannot continue, was unable to download one or more archives
29,44 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in c:\agent\_work\1\s\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\agent\_work\1\s\Wabbajack.Lib\MO2Installer.cs:line 138
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__46_0() in c:\agent\_work\1\s\Wabbajack.Lib\ABatchProcessor.cs:line 168
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 168
--- End of stack trace from previous location where exception was thrown ---
   at Wabbajack.MO2InstallerVM.Install() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 162
   at Wabbajack.InstallerVM.<>c__DisplayClass92_0.<<-ctor>b__69>d.MoveNext() in c:\agent\_work\1\s\Wabbajack\View Models\Installers\InstallerVM.cs:line 365

**Comment by ForgottenGlory** [comment]
I know.
